sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.1
    - cabal-install-1.22
    - happy
    - alex


before_install:
- export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH


install:
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests


script:
 - cabal configure --enable-tests
 - cabal test